--1번. 사원 번호와 사원명과 부서명과 부서의 위치를 출력하는 뷰(VIEW_LOC)를 작성하라
CREATE VIEW VIEW_LOC
AS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME, D.LOCATION_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT * FROM VIEW_LOC;
DESC VIEW_LOC;
--2번. 30번 부서소속 사원의 이름과 입사일과 부서명을 출력하는 뷰(VIEW_DEPT30)을 작성하라
CREATE VIEW VIEW_DEPT30
AS
SELECT E.FIRST_NAME, E.HIRE_DATE, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.DEPARTMENT_ID = 30;

SELECT * FROM VIEW_DEPT30;

--3번. 부서별 최대 급여 정보를 가지는 뷰(VIEW_DEPT_MAXSAL)을 생성하라
SELECT DEPARTMENT_ID,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

CREATE VIEW VIEW_DEPT_MAXSAL
AS
SELECT DEPARTMENT_ID,MAX(SALARY) SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT * FROM VIEW_DEPT_MAXSAL;

--4번. 급여를 많이 받는 순서대로 3명만 출력하는 뷰(VIEW_SAL_TOP03)과 인라인 뷰로 작성하라
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES ORDER BY SALARY DESC;

SELECT ROWNUM, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM (SELECT FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM <= 3;






