--이미 존재하는 EMP01 테이블에 입사일 칼럼 (CAEDATE)을 날짜형으로 추가하라
ALTER TABLE EMP01 ADD CAEDATE DATE;

--  고객 테이블 생성을 위한 필드(속성을 부여한 데이터)
CREATE TABLE TB_CUSTOMER(
    CUSTOMER_CD CHAR(7) NOT NULL,
    CUSTIMER_NM VARCHAR2(20) NOT NULL,
    MW_FLG CHAR(1) NOT NULL,
    BIRTH_DAY CHAR(8) NOT NULL,
    PHONE_NUMBER VARCHAR2(16),
    EMAIL VARCHAR(30),
    TOTAL_POINT NUMBER(10),
    REG_DTTM CHAR(14)
);
ALTER TABLE TB_CUSTOMER ADD CONSTRAINT CUSTO_PK PRIMARY KEY(CUSTOMER_CD);
ALTER TABLE TB_CUSTOMER MODIFY MW_FLG CHAR(1) CHECK(MW_FLG IN('M', 'F'));
ALTER TABLE TB_CUSTOMER MODIFY TOTAL_POINT NUMBER(10) DEFAULT '0';
SELECT * FROM TB_CUSTOMER;
DESC TB_CUSTOMER;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TB_CUSTOMER';

CREATE TABLE STUDENT_GT(
    STU_NUM NUMBER(6) NOT NULL,
    STU_NAME VARCHAR(9) NOT NULL,
    STU_KOR NUMBER(9) DEFAULT '0',
    STU_MATH NUMBER(9) DEFAULT '0',
    STU_ENG NUMBER(9) DEFAULT '0',
    STU_TOTAL NUMBER(9) DEFAULT '0',
    STU_AVG NUMBER(9) DEFAULT '0',
    STU_DEP NUMBER(2)
);
ALTER TABLE STUDENT_GT ADD CONSTRAINT STU_PK PRIMARY KEY(STU_DEP);
ALTER TABLE STUDENT_GT DROP CONSTRAINT STU_PK;
INSERT INTO STUDENT_GT VALUES (111111,'ANNE',10,10,10,30,10,10);

CREATE TABLE STUDENT_DEPT(
    STU_DEP NUMBER(2) NOT NULL,
    DEP_NAME VARCHAR2(10)
);
ALTER TABLE STUDENT_DEPT ADD CONSTRAINT DEPT_PK PRIMARY KEY(STU_DEP);
ALTER TABLE STUDENT_DEPT
ADD CONSTRAINT FK_STUDENT_GT
FOREIGN KEY(STU_DEP) REFERENCES STUDENT_GT(STU_DEP);


INSERT INTO STUDENT_DEPT VALUES (10,'전자기');
INSERT INTO STUDENT_DEPT VALUES (20,'IT');
INSERT INTO STUDENT_DEPT VALUES (30,'전자기');

