--1번.EMPLOYEES테이블에 등록된 총 사원의 수와 급여의 합, 급여의 평균 을 변수에 대입하여 출력해보자.
DECLARE
    COUNTEMP NUMBER;
    SUMSALARY NUMBER;
    AVGSALARY NUMBER(10,2);
BEGIN
    SELECT COUNT(*), SUM(SALARY), AVG(SALARY) INTO COUNTEMP, SUMSALARY, AVGSALARY FROM EMPLOYEES;

    
    DBMS_OUTPUT.PUT_LINE('총 사원의 수 = ' || COUNTEMP);
    DBMS_OUTPUT.PUT_LINE('급여의 합 = ' || SUMSALARY);
    DBMS_OUTPUT.PUT_LINE('급여의 평균 = ' || AVGSALARY);
END;
/

--2번. 'Clara'사원의 직무, 급여, 입사일자, 커미션, 부서명을 변수에 대입하여 출력해보자.
DECLARE
    EMP_JOB EMPLOYEES.JOB_ID%TYPE;
    EMP_SALARY EMPLOYEES.SALARY%TYPE;
    EMP_HIRE EMPLOYEES.HIRE_DATE%TYPE;
    EMP_COMM EMPLOYEES.COMMISSION_PCT%TYPE;
    DEP_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    SELECT EMPLOYEE_ID, FIRST_NAME INTO EMP_ID, EMP_NAME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = WHERE UPPER('CLARA');
    DBMS_OUTPUT.PUT_LINE('총 사원의 수 = ' || COUNTEMP);
    DBMS_OUTPUT.PUT_LINE('총 사원의 수 = ' || COUNTEMP);
    DBMS_OUTPUT.PUT_LINE('총 사원의 수 = ' || COUNTEMP);
    DBMS_OUTPUT.PUT_LINE('총 사원의 수 = ' || COUNTEMP);
    DBMS_OUTPUT.PUT_LINE('총 사원의 수 = ' || COUNTEMP);
END;
/

SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Clara';