SELECT E.EMP_NO, E.EMP_NAME, E.EMP_POSITION, E.BIRTH_DATE, E.JOIN_DATE, E.PHONE_NUMBER, L.REMAIN_DAY, E.IS_ADMIN 
FROM EMPLOYEE E, LEAVE_BALANCE L
WHERE E.EMP_NO = L.EMP_NO;


SELECT * FROM EMPLOYEE;
SELECT * FROM LEAVE_BALANCE;
SELECT * FROM LEAVE_REQUEST;

INSERT INTO LEAVE_BALANCE VALUES (LEAVE_BALANCE_SEQ.NEXTVAL, 1, '2025-01-01', 15);
INSERT INTO LEAVE_BALANCE VALUES (LEAVE_BALANCE_SEQ.NEXTVAL, 2, '2025-01-01', 15);
INSERT INTO LEAVE_BALANCE VALUES (LEAVE_BALANCE_SEQ.NEXTVAL, 3, '2025-01-01', 15);
INSERT INTO LEAVE_BALANCE VALUES (LEAVE_BALANCE_SEQ.NEXTVAL, 4, '2025-01-01', 15);
INSERT INTO LEAVE_BALANCE VALUES (LEAVE_BALANCE_SEQ.NEXTVAL, 5, '2025-01-01', 13);

SELECT E.EMP_NO, E.EMP_NAME, E.EMP_POSITION, E.BIRTH_DATE, E.JOIN_DATE, E.PHONE_NUMBER, L.REMAIN_DAY
FROM EMPLOYEE E, LEAVE_BALANCE L
WHERE E.EMP_NO = L.EMP_NO AND E.EMP_NO =1;

COMMIT;

UPDATE EMPLOYEE
SET EMP_NAME = '중급대리', EMP_PASSWORD = '123456' ,EMP_POSITION = '대리', BIRTH_DATE = '98-07-03', JOIN_DATE = '25-06-02', PHONE_NUMBER = '010-9910-4232',  IS_ADMIN = 1
WHERE EMP_NO = 5;

INSERT INTO EMPLOYEE VALUES (EMPLOYEE_SEQ.nextval,'123456','하급사원','사원','2000-01-01',SYSDATE,'010-9999-0000',1);

DESC LEAVE_REQUEST;
DESC LEAVE_BALANCE;
DESC EMPLOYEE;

DELETE FROM EMPLOYEE WHERE EMP_NO = 22;
SELECT L.REQ_NO, L.EMP_NO, E.EMP_NAME, L.LEAVE_TYPE, L.START_DATE, L.END_DATE, L.REASON, L.STATUS FROM LEAVE_REQUEST L, EMPLOYEE E WHERE L.EMP_NO = E.EMP_NO;

INSERT INTO LEAVE_REQUEST (REQ_NO, EMP_NO, LEAVE_TYPE, START_DATE, END_DATE, REASON) 
VALUES (LEAVE_REQUEST_SEQ.NEXTVAL,  1 ,  '연차',  '2025-06-10' ,  '2025-06-13', '여름휴가');

INSERT INTO LEAVE_REQUEST (REQ_NO, EMP_NO, LEAVE_TYPE, REASON) 
VALUES (LEAVE_REQUEST_SEQ.NEXTVAL,  3 ,  '병가', '많이 아픔');

DROP TABLE LEAVE_REQUEST;

CREATE TABLE LEAVE_REQUEST(
    REQ_NO NUMBER(4) NOT NULL,
    EMP_NO NUMBER(4) NOT NULL,
    LEAVE_TYPE VARCHAR2(10) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    REASON VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'STAY'
);
ALTER TABLE LEAVE_REQUEST ADD CONSTRAINT REQ_NO_PK PRIMARY KEY(REQ_NO);
ALTER TABLE LEAVE_REQUEST ADD CONSTRAINT REQ_EMP_NO_FK FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO);
CREATE SEQUENCE LEAVE_REQUEST_SEQ 
START WITH 1 
INCREMENT BY 1;

SELECT EMP_NO, LEAVE_TYPE, REASON, STATUS FROM LEAVE_REQUEST WHERE EMP_NO = 3;


UPDATE LEAVE_REQUEST SET STATUS = 'APPROVE' WHERE EMP_NO = ? AND LEAVE_TYPE = '연차';

UPDATE LEAVE_REQUEST SET STATUS = 'REFUSE' WHERE EMP_NO = ? AND LEAVE_TYPE = '연차';

UPDATE LEAVE_REQUEST SET STATUS = 'APPROVE' WHERE EMP_NO = ? AND LEAVE_TYPE = '병가';

UPDATE LEAVE_REQUEST SET STATUS = 'REFUSE' WHERE EMP_NO = ? AND LEAVE_TYPE = '병가';

SELECT E.EMP_NO, E.EMP_NAME, E.EMP_POSITION, R.LEAVE_TYPE, R.START_DATE, R.END_DATE, R.REASON, R.STATUS
FROM EMPLOYEE E, LEAVE_REQUEST R
WHERE E.EMP_NO = R.EMP_NO;

UPDATE (SELECT B.REMAIN_DAY, R.STATUS FROM LEAVE_BALANCE B, LEAVE_REQUEST R
WHERE B.EMP_NO = R.EMP_NO)
SET B.REMAI



