--회원관리 테이블
CREATE TABLE MEMBER(
    MEMBER NUMBER,
    ID VARCHAR2(30) NOT NULL check(regexp_like(ID,'^[가-힣a-zA-Z0-9]{3,10}$')),
    PW VARCHAR2(30) NOT NULL check(regexp_like(PW,'^[a-zA-Z0-9]{3,10}$')),
    NAME VARCHAR2(20) NULL check(regexp_like(NAME,'^[가-힣a-zA-Z0-9]{3,10}$'))
);
ALTER TABLE Member ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY(MEMBER);
-- Member 시퀀스 생성
    DROP SEQUENCE Member_SEQ;
    CREATE SEQUENCE MEMBER_SEQ
    START WITH 1
    INCREMENT BY 1;

--CURD
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'ASD', '1234', 'HONG');
UPDATE MEMBER SET ID = 'QWER', PW ='1234', NAME ='KILL' WHERE MEMBER = 1;
SELECT * FROM MEMBER WHERE MEMBER > 0 ORDER BY MEMBER DESC;
SELECT * FROM MEMBER WHERE MEMBER = ?;
DELETE FROM MEMBER WHERE MEMBER =1;