--'jking'이란 이메일을 갖은 직원의 이름과 급여와 커미션을 출력하라(INITCAP, UPPER)
SELECT INITCAP(FIRST_NAME), SALARY, COMMISSION_PCT FROM EMPLOYEES WHERE EMAIL = UPPER('jking');
--SELECT * FROM EMPLOYEES WHERE
--이름이 6글자 이상인 직원의 전화번호와 이름과 급여를 출력하라.
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES WHERE LENGTH(FIRST_NAME)>=6;

--03년도에 입사한 사원 알아내기(비교연산자와 AND 연산자, BETWEEN AND 연산자, SUBSTR함수)
SELECT * FROM EMPLOYEES WHERE SUBSTR(HIRE_DATE,1,2)=03;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '03/01/01' AND '03/12/31';

--이름이 k로 끝나는 직원을 검색(LIKE 연산자와 와일드카드(%), SUBSTR함수)
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%k';

--직원 번호가 짝수인 직원들의 직원번호와 이름과 직급을 출력하라.
SELECT EMPLOYEE_ID, JOB_ID FROM EMPLOYEES WHERE MOD(EMPLOYEE_ID,2) = 0;

--모든 직원은 자신의 상관(MANAGER_ID)이 있다. 하지만 EMPLOYEES 테이블에 유일하게
--상관이 없는 로우가 있는데 그 사원의 MANAGER_ID 칼럼 값이 NULL이다.
--상관이 없는 대표이사만 출력하되 MANAGER_ID 칼럼 값 NULL 대신 CEO로 출력한다.
SELECT FIRST_NAME, NVL2(MANAGER_ID,'','CEO') MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL;

--부서별에 따라 급여를 인상하도록 하자. (직원번호, 직원명, 직급, 급여) 부서명이
--'Marketing'인 직원은 5%, 'Purchasing'인 사원은 10%, 'Human Resources'인 사원은 15%,
--' IT'인 직원은 20%인 인상한다.
UPDATE EMPLOYEES SET SALARY = ROUND(SALARY*1.05) WHERE JOB_ID LIKE 'MK%';
UPDATE EMPLOYEES SET SALARY = ROUND(SALARY*1.1) WHERE JOB_ID LIKE 'PU%';
UPDATE EMPLOYEES SET SALARY = ROUND(SALARY*1.15) WHERE JOB_ID LIKE 'HR%';
UPDATE EMPLOYEES SET SALARY = ROUND(SALARY*1.20) WHERE JOB_ID LIKE 'IT%';
SELECT * FROM EMPLOYEES;

--JOB의 종류가 몇 개인지 즉, 중복되지
SELECT COUNT(DISTINCT JOB_ID) FROM EMPLOYEES;
--서브쿼리
--SELECT COUNT(*) AS 직업의갯수 FROM (SELECT JOB_ID FROM EMPLOYEES GROUP BY JOB_ID);



--테이블 삭제 후 EMP01테이블 생성
DROP TABLE EMP01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9) NOT NULL,
    MGR NUMBER(4) NOT NULL,
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2) NOT NULL,
    DEPTNO NUMBER(2)
);
ALTER TABLE EMP01 MODIFY COMM NUMBER(7,2) NULL;
ALTER TABLE EMP01 MODIFY MGR NUMBER(4) NULL;
--EMP01 데이터 추가
ALTER TABLE EMP01 ADD CONSTRAINT EMP01_PK PRIMARY KEY(EMPNO);
ALTER TABLE EMP01 ADD CONSTRAINT EMP01_UK UNIQUE(ENAME);
ALTER TABLE EMP01 ADD CONSTRAINT EMP01_CK CHECK(SAL BETWEEN 1000 AND 200000);
ALTER TABLE EMP01 RENAME COLUMN COMM TO COMMISSION;
ALTER TABLE EMP01 ADD CONSTRAINT EMP01_DEPT_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO); 
ALTER TABLE EMP_01 DROP CONSTRAINT EMP01_UK

INSERT INTO EMP01 VALUES (7369,'SMITH','CLEAK',7826,'80/12/17',800,NULL,20);
INSERT INTO EMP01 VALUES (7499,'ALLEN','SALESMAN',7369,'87/12/20',1600,300,30);
INSERT INTO EMP01 VALUES (7839,'KING','PRESIDENT',NULL,'81/02/08',5000,'',10);


--MEMBERS 테이블 생성
CREATE TABLE MEMBERS(
    ID VARCHAR2(20),
    NAME VARCHAR2(20),
    REGNO VARCHAR2(13),
    HP VARCHAR2(13),
    ADDRESS VARCHAR2(100)
);
ALTER TABLE MEMBERS ADD CONSTRAINT ID_PK PRIMARY KEY (ID);



