
--모두입력해야한다
CREATE TABLE BOARD( 
    BOARD_NO NUMBER,              -- pk
    TITLE VARCHAR2(20) NOT NULL CHECK(REGEXP_LIKE(TITLE,'^[가-힣]{3,20}$')), -- 한글로만 이루어져야한다. 최소 3글자 최대 20자 까지 허용
    CONTENT VARCHAR2(1000) NOT NULL,  -- content 글자 사이즈는 1000자로 할당
    WRITER VARCHAR2(10) NOT NULL CHECK(REGEXP_LIKE(WRITER,'^[가-힣A-Za-z]{2,10}$')), -- 한글과 영문자 구성되어야하며 최소 2글자에서 최대 10글자로 허용
    REG_DATE DATE DEFAULT SYSDATE -- 날짜형식으로 지정하고 미지정시 현재시각으로 자동 저장한다.
);

--GENDER CHAR(1) NOT NULL CHECK(GENDER IN ('M','F')),
--SCORE NUMBER(3) NOT NULL CHECK(SCORE BETWEEN 0 AND 100),

ALTER TABLE BOARD ADD CONSTRAINT BOARD_PK PRIMARY KEY(BOARD_NO);

CREATE SEQUENCE BOARD_SEQ 
START WITH 1 
INCREMENT BY 1;

DROP SEQUENCE JDBCBOARD_SEQ;

DROP TABLE JDBCBOARD;

SELECT * FROM BOARD;
COMMIT;