CREATE TABLE MYBATISMEMBER( 
NO NUMBER,
ID VARCHAR2(100) NOT NULL, 
PWD VARCHAR2(1000) NULL, 
NAME VARCHAR2(50) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE,
PRIMARY KEY (NO)
);

CREATE SEQUENCE MYBATISMEMBER_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM MYBATISMEMBER;